### ISSUE TITLE
Rails 4.0.3 installation failed due to config/secrets.yml

### ISSUE THREAD

**Issue by Aktanee** [ForestAdmin/forest-rails#109]
Step to reproduce :
rails -v @=> 4.0.3
bundle install
rails g forest_liana:install key

```bash
Instance method "destroyed?" is already defined in ActiveRecord::Base, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.
       route  mount ForestLiana::Engine => '/forest'
 initializer  forest_liana.rb

Forest generated a random authentication secret to secure the data access of your local project.
You can change it at any time in your config/secrets.yml file.

      insert  config/secrets.yml
/Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:99:in `binread': No such file or directory @ rb_sysopen - /Users/antoine/code/orson-rb/config/secrets.yml (Errno::ENOENT)
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:99:in `replace!'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:60:in `invoke!'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/actions.rb:95:in `action'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:31:in `insert_into_file'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/forest_liana-1.5.11/lib/generators/forest_liana/install_generator.rb:23:in `install'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `each'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `invoke_all'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@global/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/railties-4.0.3/lib/rails/generators.rb:156:in `invoke'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/railties-4.0.3/lib/rails/commands/generate.rb:11:in `<top (required)>'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `require'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `block in require'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `require'
	from /Users/antoine/.rvm/gems/ruby-2.1.5@pikock-rb/gems/railties-4.0.3/lib/rails/commands.rb:48:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by arnaudbesnier** [comment]
Hi @Aktanee , thanks for the report.
That's true, the current liana raise an error due too missing `secrets.yml` on installation for Rails versions older than Rails 4.1.0 (where the `secrets.yml` feature was introduced).

To make it work you can install a gem to backport the "secrets" feature to old Rails versions.
The following gem is an option that should work for you:
https://github.com/pixeltrix/rails-secrets

🌲 🌲 🌲
