### ISSUE TITLE
[Crash] Forest with Rails 5.1.0.rc1

### ISSUE THREAD

**Issue by josephpage** [ForestAdmin/forest-rails#120]
The first Release Candidate release of Rails 5.1 is here !

And here is the crash test with Forest. 💥 

At app launch :
```
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::ActionSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of ActionSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::ActionController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of ActionController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::ActionSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of ActionSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::ActionController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of ActionController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::ActionSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of ActionSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::ActionController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of ActionController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::ActionSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of ActionSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::ActionController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of ActionController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: already initialized constant ForestLiana::UserSpace::IntegrationSerializer
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/serializers/forest_liana/serializer_factory.rb:15: warning: previous definition of IntegrationSerializer was here
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: already initialized constant ForestLiana::IntegrationController
web_1     | /usr/local/bundle/gems/forest_liana-1.5.17/app/services/forest_liana/controller_factory.rb:11: warning: previous definition of IntegrationController was here
web_1     | => Booting Puma
web_1     | => Rails 5.1.0.rc1 application starting in development on http://0.0.0.0:3000
web_1     | => Run `rails server -h` for more startup options
web_1     | Puma starting in single mode...
web_1     | * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
web_1     | * Min threads: 5, max threads: 5
web_1     | * Environment: development
web_1     | * Listening on tcp://0.0.0.0:3000
web_1     | Use Ctrl-C to stop
```

After a login attempt :

```
web_1     | Started POST "/forest/sessions" for 192.168.99.1 at 2017-03-27 16:19:53 +0000
web_1     |    (0.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
web_1     |   
web_1     | ActionController::RoutingError (uninitialized constant ForestLiana::ActionController::Base):
web_1     |   
web_1     | forest_liana (1.5.17controllers) forest_liana/sessions_controller.rb:2:in `<module:ForestLiana>'
web_1     | forest_liana (1.5.17controllers) forest_liana/sessions_controller.rb:1:in `<top (required)>'
web_1     | activesupport (5.1.0.rc1) lib/active_support/dependencies/interlock.rb:12:in `block in loading'
web_1     | activesupport (5.1.0.rc1) lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
web_1     | activesupport (5.1.0.rc1) lib/active_support/dependencies/interlock.rb:11:in `loading'
web_1     | activesupport (5.1.0.rc1) lib/active_support/inflector/methods.rb:271:in `const_get'
web_1     | activesupport (5.1.0.rc1) lib/active_support/inflector/methods.rb:271:in `block in constantize'
web_1     | activesupport (5.1.0.rc1) lib/active_support/inflector/methods.rb:267:in `each'
web_1     | activesupport (5.1.0.rc1) lib/active_support/inflector/methods.rb:267:in `inject'
web_1     | activesupport (5.1.0.rc1) lib/active_support/inflector/methods.rb:267:in `constantize'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/http/request.rb:82:in `controller_class'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/routing/route_set.rb:43:in `controller'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/routing/route_set.rb:29:in `serve'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/journey/router.rb:33:in `each'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/journey/router.rb:33:in `serve'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/routing/route_set.rb:836:in `call'
web_1     | rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
web_1     | railties (5.1.0.rc1) lib/rails/engine.rb:522:in `call'
web_1     | railties (5.1.0.rc1) lib/rails/railtie.rb:185:in `public_send'
web_1     | railties (5.1.0.rc1) lib/rails/railtie.rb:185:in `method_missing'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/journey/router.rb:33:in `each'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/journey/router.rb:33:in `serve'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/routing/route_set.rb:836:in `call'
web_1     | rack (2.0.1) lib/rack/etag.rb:25:in `call'
web_1     | rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
web_1     | rack (2.0.1) lib/rack/head.rb:12:in `call'
web_1     | activerecord (5.1.0.rc1) lib/active_record/migration.rb:556:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
web_1     | activesupport (5.1.0.rc1) lib/active_support/callbacks.rb:97:in `run_callbacks'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/executor.rb:12:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
web_1     | railties (5.1.0.rc1) lib/rails/rack/logger.rb:36:in `call_app'
web_1     | railties (5.1.0.rc1) lib/rails/rack/logger.rb:24:in `block in call'
web_1     | activesupport (5.1.0.rc1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
web_1     | activesupport (5.1.0.rc1) lib/active_support/tagged_logging.rb:26:in `tagged'
web_1     | activesupport (5.1.0.rc1) lib/active_support/tagged_logging.rb:69:in `tagged'
web_1     | railties (5.1.0.rc1) lib/rails/rack/logger.rb:24:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
web_1     | rack (2.0.1) lib/rack/runtime.rb:22:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/executor.rb:12:in `call'
web_1     | actionpack (5.1.0.rc1) lib/action_dispatch/middleware/static.rb:125:in `call'
web_1     | rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
web_1     | rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
web_1     | railties (5.1.0.rc1) lib/rails/engine.rb:522:in `call'
web_1     | puma (3.8.2) lib/puma/configuration.rb:224:in `call'
web_1     | puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
web_1     | puma (3.8.2) lib/puma/server.rb:435:in `process_client'
web_1     | puma (3.8.2) lib/puma/server.rb:299:in `block in run'
web_1     | puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
web_1     | Error during failsafe response: uninitialized constant ForestLiana::ActionController::Base
web_1     |   /usr/local/bundle/gems/forest_liana-1.5.17/app/controllers/forest_liana/sessions_controller.rb:2:in `<module:ForestLiana>'
web_1     |   /usr/local/bundle/gems/forest_liana-1.5.17/app/controllers/forest_liana/sessions_controller.rb:1:in `<top (required)>'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies/interlock.rb:11:in `loading'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/inflector/methods.rb:271:in `const_get'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/inflector/methods.rb:271:in `block in constantize'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/inflector/methods.rb:267:in `each'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/inflector/methods.rb:267:in `inject'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/inflector/methods.rb:267:in `constantize'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/http/request.rb:82:in `controller_class'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/http/parameters.rb:88:in `set_binary_encoding'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/http/parameters.rb:58:in `parameters'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/http/mime_negotiation.rb:63:in `block in formats'
web_1     |   /usr/local/bundle/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch'
web_1     |   /usr/local/bundle/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch_header'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/http/mime_negotiation.rb:61:in `formats'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/public_exceptions.rb:22:in `call'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
web_1     |   /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/rack/logger.rb:36:in `call_app'
web_1     |   /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/rack/logger.rb:24:in `block in call'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/tagged_logging.rb:26:in `tagged'
web_1     |   /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/tagged_logging.rb:69:in `tagged'
web_1     |   /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/rack/logger.rb:24:in `call'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
web_1     |   /usr/local/bundle/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/executor.rb:12:in `call'
web_1     |   /usr/local/bundle/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/static.rb:125:in `call'
web_1     |   /usr/local/bundle/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
web_1     |   /usr/local/bundle/gems/rack-cors-0.4.1/lib/rack/cors.rb:81:in `call'
web_1     |   /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/engine.rb:522:in `call'
web_1     |   /usr/local/bundle/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
web_1     |   /usr/local/bundle/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
web_1     |   /usr/local/bundle/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
web_1     |   /usr/local/bundle/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
web_1     |   /usr/local/bundle/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by arnaudbesnier** [comment]
@josephpage thank for the report!

**Comment by josephpage** [comment]
The warnings at boot were introduced with 1.5.14. (no warning with 1.5.13)
but the crash at login is present in 1.5.13 too

**Comment by SeyZ** [comment]
Hey @josephpage I think we've fixed this issue in this commit: https://github.com/ForestAdmin/forest-rails/commit/78e2d674d7a61d02287a0e79a597874efe98deda

Can you try to upgrade to the version 1.5.18 ? 
`$ bundle update --source forest_liana`

Thank you :)

**Comment by SeyZ** [comment]
Of course, feel free to reopen this issue if you still have the problem

**Comment by SeyZ** [comment]
I was wrong, @arnaudbesnier just told me it's certainly related to the version of Rails (5.1). I'll keep you updated

**Comment by SeyZ** [comment]
@josephpage I would love to know if you still have the issue using the version `1.5.20`.
`$ bundle update --source forest_liana`

Thanks!

**Comment by josephpage** [comment]
No more crashes with 1.5.20. Thanks @SeyZ !
But warnings at boot are always there.

Extract from my Gemfile :
```
ruby '2.4.1' # 2.4.1p111 (2017-03-22 revision 58053)

gem 'pg', '~> 0.18' # postgresql as the database for Active Record
gem 'puma', '~> 3.0' # web server
gem 'rack-cors' # making cross-origin AJAX possible (CORS)
gem 'rails', '~> 5.1.0.rc1' # the famous Ruby on Rails !

gem 'active_model_serializers', '~> 0.10.4' # json:api serializer for rails models
gem 'forest_liana', '1.5.20' # Magic admin interface
```

**Comment by josephpage** [comment]
Warnings are now over.
Thanks @SeyZ @arnaudbesnier  :1st_place_medal:

**Comment by randallb** [comment]
We're getting this issue in 1.7.4 on rails 4.2 or rails 5.1

**Comment by arnaudbesnier** [comment]
Hi @randallb,
can you provide more details about your issue?

- Did the issue appear after a liana upgrade? or a Rails upgrade?
- Can you send the logs you have?

Thank you.
