### ISSUE TITLE
Forest prevents app/console from starting when disconnected from internet

### ISSUE THREAD

**Issue by josephpage** [ForestAdmin/forest-rails#132]
I was disconnected from internet, I just tried to launch `rails console` and 💥 : 

```
/usr/local/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to forestadmin-server.herokuapp.com:443 (getaddrinfo: Name or service not known) (SocketError)
	from /usr/local/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:876:in `start'
	from /usr/local/bundle/gems/forest_liana-1.5.23/lib/forest_liana/bootstraper.rb:146:in `send_apimap'
	from /usr/local/bundle/gems/forest_liana-1.5.23/lib/forest_liana/bootstraper.rb:28:in `perform'
	from /usr/local/bundle/gems/forest_liana-1.5.23/lib/forest_liana/engine.rb:51:in `block in <class:Engine>'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `run'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:58:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/application.rb:353:in `initialize!'
	from /app/config/environment.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

I understand I can't use Forest offline, but my app is not only about 🌳🌳🌳  . Sometimes I want to work on a 🚄 , at 🏠 without being connected, or just... one day... Forest servers could be down. The gem should gracefully handle this (rare) case.

**Comment by arnaudbesnier** [comment]
Hi @josephpage Forest is supposed to support applications start while offline. It is either a regression or an issue with Rails 5.1.

**Comment by arnaudbesnier** [comment]
I confirm that this is an issue related with Rails 5, there is not such an issue with Rails 4.

**Comment by arnaudbesnier** [comment]
Ok the fix is in review!

**Comment by josephpage** [comment]
Oh !! When talking about offline backend : 

```
/usr/local/bundle/gems/json-2.0.4/lib/json/common.rb:156:in `parse': 751: unexpected token at '<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>' (JSON::ParserError)
	from /usr/local/bundle/gems/json-2.0.4/lib/json/common.rb:156:in `parse'
	from /usr/local/bundle/gems/forest_liana-1.5.24/lib/forest_liana/bootstraper.rb:154:in `block in send_apimap'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /usr/local/bundle/gems/forest_liana-1.5.24/lib/forest_liana/bootstraper.rb:146:in `send_apimap'
	from /usr/local/bundle/gems/forest_liana-1.5.24/lib/forest_liana/bootstraper.rb:28:in `perform'
	from /usr/local/bundle/gems/forest_liana-1.5.24/lib/forest_liana/engine.rb:51:in `block in <class:Engine>'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `run'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:58:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.1.0.rc1/lib/rails/application.rb:353:in `initialize!'
	from /app/config/environment.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Seems the 🌳🌲🌳  is 🔥  !

**Comment by arnaudbesnier** [comment]
@josephpage we just had a temporary downtime, this is ok right now.

**Comment by josephpage** [comment]
This event proves the need to be resilient not only to Errno::ECONNREFUSED  and SocketError, but all issues with the connectivity, doesn't it ?

Maybe, also upload [your own Heroku Error Pages](https://devcenter.heroku.com/articles/error-pages) with JSON inside.

**Comment by arnaudbesnier** [comment]
@josephpage I have improved the behaviour of the liana, you can review the PR if you want to.

**Comment by josephpage** [comment]
Thanks !
