### ISSUE TITLE
Filtering data through association

### ISSUE THREAD

**Issue by piotr-sokolowski** [ForestAdmin/forest-rails#151]
When trying to filter data (for chart) while using constraint on association column value, there is exception raised.
Problematic code is at https://github.com/ForestAdmin/forest-rails/blob/devel/app/services/forest_liana/operator_value_parser.rb#L52

Because of this line, `format_value` is later trying to find column which is in format "association_name:column" which obviously does not exists.

**Comment by arnaudbesnier** [comment]
Thanks for the report @piotr-sokolowski 

In order to help us reproduce and fix this issue, can you add the following elements?
- a screenshot of your chart configuration
- the error in your Rails console (stack trace?)
- the payload of the request sent by the browser to compute the chart?

That would be great!

**Comment by piotr-sokolowski** [comment]
```
Started POST "/forest/stats/subscribers" for 127.0.0.1 at 2017-05-31 11:09:44 +0200
Processing by ForestLiana::StatsController#show as HTML
  Parameters: {"type"=>"Line", "collection"=>"subscribers", "timezone"=>"+02:00", "group_by_date_field"=>"created_at", "aggregate"=>"Count", "time_range"=>"Day", "filterType"=>"and", "filters"=>[{"field"=>"created_at", "value"=>"$30DaysToDate"}, {"field"=>"status_page:subdomain", "value"=>"cognetoweb"}], "stat"=>{"type"=>"Line", "collection"=>"subscribers", "timezone"=>"+02:00", "group_by_date_field"=>"created_at", "aggregate"=>"Count", "time_range"=>"Day", "filterType"=>"and", "filters"=>[{"field"=>"created_at", "value"=>"$30DaysToDate"}, {"field"=>"status_page:subdomain", "value"=>"cognetoweb"}]}}
Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.0ms)

NoMethodError - undefined method `type' for nil:NilClass:
  forest_liana (1.6.10) app/services/forest_liana/operator_value_parser.rb:74:in `format_value'
  forest_liana (1.6.10) app/services/forest_liana/operator_value_parser.rb:56:in `get_condition'
  forest_liana (1.6.10) app/services/forest_liana/line_stat_getter.rb:36:in `block in perform'
  activesupport (4.2.7.1) lib/active_support/core_ext/object/try.rb:77:in `try!'
  activesupport (4.2.7.1) lib/active_support/core_ext/object/try.rb:63:in `try'
  forest_liana (1.6.10) app/services/forest_liana/line_stat_getter.rb:34:in `perform'
  forest_liana (1.6.10) app/controllers/forest_liana/stats_controller.rb:19:in `show'
```
https://cl.ly/0d350N2k3L35

**Comment by arnaudbesnier** [comment]
Thanks! We'll have a look at it.

**Comment by arnaudbesnier** [comment]
hey @piotr-sokolowski, your issue is now fixed, you can update your gem to the latest version (1.6.11).

Of course, you can reopen the issue if necessary
🌲🌲🌲
