### ISSUE TITLE
Activerecord uuid joins error

### ISSUE THREAD

**Issue by GabKlein** [ForestAdmin/forest-rails#37]
I'm having a weird PG error on a list view `/:id/list/:id`
I'm running on the master version of Forest, here the stack trace

```
ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  operator does not exist: uuid = character varying
LINE 1: ..." IS NULL LEFT OUTER JOIN "teams" ON "teams"."id" = "members...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  activerecord (4.2.7.1) lib/active_record/relation/finder_methods.rb:356:in `find_with_associations'
  activerecord (4.2.7.1) lib/active_record/relation.rb:639:in `exec_queries'
  activerecord (4.2.7.1) lib/active_record/relation.rb:515:in `load'
  activerecord (4.2.7.1) lib/active_record/relation.rb:243:in `to_a'
  .rvm/gems/ruby-2.3.1/bundler/gems/forest-rails-76abb4ec4053/app/services/forest_liana/resources_getter.rb:15:in `records'
  .rvm/gems/ruby-2.3.1/bundler/gems/forest-rails-76abb4ec4053/app/controllers/forest_liana/resources_controller.rb:14:in `index'
```

**Comment by SeyZ** [comment]
Hey @GabKlein 

Can you verify if your `schema.rb` file is correct? Are you sure the foreign key to your `team` table is a `uuid` and not a `string`? You should have something like this:

```
create_table "memberships", id: :uuid, default: "uuid_generate_v4()", force: true do |t|
    t.uuid     "team_id"
    t.datetime "created_at"
    t.datetime "updated_at"
   # ...
  end
```

**Comment by GabKlein** [comment]
Indeed the reference was a `string` type. Thx @SeyZ
