### ISSUE TITLE
uninitialized constant ForestLiana::OpenStruct

### ISSUE THREAD

**Issue by YoranBrondsema** [ForestAdmin/forest-rails#672]
## Expected behavior
Forest Admin to load.

## Actual behavior
It outputs an error message:
![CleanShot 2024-04-15 at 09 34 51](https://github.com/ForestAdmin/forest-rails/assets/1374412/594f9bdf-2593-40be-9b3e-e47636f9ac5b)

## Failure Logs
I'm getting an error `Records Index error: uninitialized constant ForestLiana::OpenStruct` in the logs when loading the records of a model.

```
2024-04-15T07:28:47.729599+00:00 app[web.2]: [2024-04-15 07:28:47 +0000] Forest ��🌳🌳  Records Index error: uninitialized constant ForestLiana::OpenStruct
2024-04-15T07:28:47.729600+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/lib/forest_liana/mixpanel_event.rb:2:in `<module:ForestLiana>'
2024-04-15T07:28:47.729601+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/lib/forest_liana/mixpanel_event.rb:1:in `<main>'
2024-04-15T07:28:47.729602+00:00 app[web.2]: /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-04-15T07:28:47.729602+00:00 app[web.2]: /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-04-15T07:28:47.729602+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2024-04-15T07:28:47.729603+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/skylight-6.0.4/lib/skylight/probes.rb:166:in `require'
2024-04-15T07:28:47.729605+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
2024-04-15T07:28:47.729607+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/app/serializers/forest_liana/serializer_factory.rb:42:in `get_serializer_name'
2024-04-15T07:28:47.729608+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/lib/forest_liana/bootstrapper.rb:150:in `find_serializer_class_name'
2024-04-15T07:28:47.729608+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:251:in `find_serializer_class'
2024-04-15T07:28:47.729609+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:411:in `block in serialize_primary'
2024-04-15T07:28:47.729609+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.2/lib/active_support/notifications.rb:206:in `block in instrument'
2024-04-15T07:28:47.729610+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
2024-04-15T07:28:47.729610+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.2/lib/active_support/notifications.rb:206:in `instrument'
2024-04-15T07:28:47.729610+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:407:in `serialize_primary'
2024-04-15T07:28:47.729611+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:453:in `block in serialize_primary_multi'
2024-04-15T07:28:47.729611+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:453:in `map'
2024-04-15T07:28:47.729611+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:453:in `serialize_primary_multi'
2024-04-15T07:28:47.729612+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forestadmin-jsonapi-serializers-2.0.0.pre.beta.2/lib/jsonapi-serializers/serializer.rb:331:in `serialize'
2024-04-15T07:28:47.729612+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/app/controllers/forest_liana/application_controller.rb:48:in `serialize_models'
2024-04-15T07:28:47.729612+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/app/controllers/forest_liana/resources_controller.rb:227:in `render_jsonapi'
2024-04-15T07:28:47.729613+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/app/controllers/forest_liana/resources_controller.rb:24:in `block (2 levels) in index'
2024-04-15T07:28:47.729613+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.1.3.2/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
2024-04-15T07:28:47.729613+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/forest_liana-9.2.1/app/controllers/forest_liana/resources_controller.rb:23:in `index'
2024-04-15T07:28:47.729614+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.1.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
2024-04-15T07:28:47.729614+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.1.3.2/lib/abstract_controller/base.rb:224:in `process_action'
2024-04-15T07:28:47.729614+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.1.3.2/lib/action_controller/metal/rendering.rb:165:in `process_action'
2024-04-15T07:28:47.729614+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.1.3.2/lib/abstract_controller/callbacks.rb:259:in `block in process_action'
2024-04-15T07:28:47.729614+00:00 app[web.2]: /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
...
```

It pertains to the line at https://github.com/ForestAdmin/forest-rails/blob/main/lib/forest_liana/mixpanel_event.rb#L2

Perhaps `require 'ostruct'` needs to be added to the top of the file?

## Context

* Package Version: 9.2.1 (but also tried with 9.3.2)
* Rails Version:  7.1.3.2
* Database Dialect: postgresql
* Database Version: 13.3

**Comment by nicolasalexandre9** [comment]
Hi @YoranBrondsema, 

I wasn't able to reproduce your issue, but I aggre with you `require “ostruct”` is missing. 

Can you confirme that your PR has solved your issue ? If so, I will merge your PR.

**Comment by YoranBrondsema** [comment]
Yes it does!

**Comment by nicolasalexandre9** [comment]
Nice ! It's merge, thank you for your contribution.
